[build]
  command = "npm run build:web"
  publish = "dist/client"

[functions]
  directory = "dist/server/_expo/functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200